# Railway V2 Configuration
# This file configures how Railway builds and deploys the application

[build]
# Use Nixpacks builder for automatic dependency detection
builder = "nixpacks"

# Custom build command to ensure proper compilation
buildCommand = "npm ci && npm run build"

[deploy]
# Use the Railway-specific start script
startCommand = "npm run start:railway"

# Restart policy for resilience
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 30

# Resource allocation (optional - Railway auto-scales)
# numReplicas = 1
# sleepApplication = false

[[services]]
# Web service configuration
name = "web"

# Dynamic port binding (Railway provides PORT env var)
[services.port]
env = "PORT"
default = 3000

# Service configuration
[services.config]
# Ensure proper Node.js memory allocation
maxMemory = "512Mi"
# Enable clustering for better performance
instances = 1